Repository HUHS-ReactStudy/huhs-reservation-frontend, pull requests merged in 2022-06, with the labels that each got.

#5 Feature/calendar
  src/components/Calendar.js
Labels: ✨ Feature, 🎨 Html&css

#7 Feature/application status UI
  package-lock.json
  package.json
  public/assets/doge.jpg
  src/assets/images/plus.svg
  src/components/AddScheduleButton.jsx
  src/components/ScheduleList.jsx
  src/components/ScheduleListItem.jsx
Labels: ✨ Feature, ⚙ Setting, 🎨 Html&css

#6 Feature/UI student number input
  src/components/InputStudentNumber.jsx
Labels: 🙋‍♂️ Question, 🎨 Html&css

#12 Feature/add pr template and prevent pull down refresh
  .github/PULL_REQUEST_TEMPLATE.md
  src/styles/GlobalStyle.js
Labels: 📃 Docs, 🎨 Html&css

#13 Feature/calendar new feat
  src/components/Calendar.js
  src/components/Week.js
Labels: ✨ Feature

#14 💄 Design: edit date color
  src/components/Week.js
Labels: 🎨 Html&css

#15 Feature/api application status
  src/App.js
  src/components/AddScheduleButton.jsx
  src/components/Calendar.js
  src/components/InputForm/CreateContext.jsx
  src/components/InputForm/FormBody.jsx
  src/components/InputForm/InformationBox.jsx
  src/components/InputForm/TimeSetBox.jsx
  src/components/InputStudentNumber.jsx
  src/components/ScheduleList.jsx
  src/components/ScheduleListItem.jsx
  src/index.js
Labels: ✨ Feature, 📬 API, 🎨 Html&css

#20 Wjdgml3834 feature/add readme.md
  README.md
Labels: 📃 Docs

#21 📝 Update README.md
  README.md
Labels: 📃 Docs

#22 📝 Update ReadMe Feeling
  README.md
Labels: 📃 Docs

#23 📝 Update: ReadMe Feeling msik
  README.md
Labels: 📃 Docs

#25 📝 Update README.md
  README.md
Labels: 📃 Docs

#26 📝 Update: update README.md
  README.md
Labels: 📃 Docs
